name=Polaris
version=0.0.1
author=Pedro Dias <77pedrodias@gmail.com>
maintainer=Pedro Dias <77pedrodias@gmail.com>
sentence=Easy control for multiple components on Arduino
paragraph=Polaris is an Arduino library designed to simplify the management of multiple hardware components. It caters to beginners and students by providing an easy-to-use interface, while still offering advanced features for experienced users who require more control and flexibility.
category=Sensor
url=https://github.com/77pedrodias/polaris
architectures=*